# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_spline <- function(quantiles, alphas, yp1, ypp) {
    .Call(`_quantspacing_c_spline`, quantiles, alphas, yp1, ypp)
}

matrix_mult <- function(A, B) {
    .Call(`_quantspacing_matrix_mult`, A, B)
}

transpose <- function(A) {
    .Call(`_quantspacing_transpose`, A)
}

invert_two <- function(A) {
    .Call(`_quantspacing_invert_two`, A)
}

c_splint <- function(y, quantiles, alphas, y2, tail_param_u, tail_param_l, tails, distn) {
    .Call(`_quantspacing_c_splint`, y, quantiles, alphas, y2, tail_param_u, tail_param_l, tails, distn)
}

spacingsToQuantiles_C <- function(spacingCoef, data, jstar) {
    .Call(`_quantspacing_spacingsToQuantiles_C`, spacingCoef, data, jstar)
}

c_spline_quant_comb <- function(y, quantiles, alphas, tails, distn) {
    .Call(`_quantspacing_c_spline_quant_comb`, y, quantiles, alphas, tails, distn)
}

c_spline_comb <- function(y, quantiles, alphas, tails, distn) {
    .Call(`_quantspacing_c_spline_comb`, y, quantiles, alphas, tails, distn)
}

c_spline_comb_track <- function(y, quantiles, alphas, tails, distn) {
    .Call(`_quantspacing_c_spline_comb_track`, y, quantiles, alphas, tails, distn)
}

c_splincomb <- function(y, quantiles_full, alphas_full, tails, distn) {
    .Call(`_quantspacing_c_splincomb`, y, quantiles_full, alphas_full, tails, distn)
}

